apiVersion: apps/v1
kind: Deployment
metadata:
  name: mac-deployment
  namespace: fiveg-virtualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mac-service
  template:
    metadata:
      labels:
        app: mac-service
    spec:
      containers:
      - name: mac-service
        image: your-docker-registry/mac-service:v1
        ports:
        - containerPort: 8082
        env:
        - name: MAC_SERVICE_PORT
          value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: mac-service
  namespace: fiveg-virtualization
spec:
  selector:
    app: mac-service
  ports:
  - name: http
    port: 8082
    targetPort: 8082
