apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdcp-deployment
  namespace: fiveg-virtualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdcp-service
  template:
    metadata:
      labels:
        app: pdcp-service
    spec:
      containers:
      - name: pdcp-service
        image: your-docker-registry/pdcp-service:v1
        ports:
        - containerPort: 8083
        env:
        - name: PDCP_SERVICE_PORT
          value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: pdcp-service
  namespace: fiveg-virtualization
spec:
  selector:
    app: pdcp-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
