apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrm-deployment
  namespace: fiveg-virtualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rrm-service
  template:
    metadata:
      labels:
        app: rrm-service
    spec:
      containers:
      - name: rrm-service
        image: your-docker-registry/rrm-service:v1
        ports:
        - containerPort: 8081
        env:
        - name: RRM_SERVICE_PORT
          value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: rrm-service
  namespace: fiveg-virtualization
spec:
  selector:
    app: rrm-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
